services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: lumilaya
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - nginx-network
      - mysql-network
      - redis-network

# Réseaux externes existants
networks:
  nginx-network:
    external: true
  mysql-network:
    external: true
  redis-network:
    external: true

